### ISSUE TITLE
Automatically detect private/public addresses

### ISSUE THREAD

**Issue by jawnsy** [GoogleCloudPlatform/cloud-sql-proxy#1597]
## Feature Description

Version 1 of the proxy seems to automatically detect that the instance is running on a private address and connect to that. In contrast, Version 2 requires us to provide the `--private-ip` flag.

In situations where the instance does not have a public address, I think it would be preferable for the proxy to connect to the private addresses automatically.

## Alternatives Considered
*Are there any workaround or third party tools to replicate this behavior? Why would adding this feature be preferred over them?*

A workaround is to use Version 1 of the proxy or pass the `--private-ip` flag explicitly. However, given that this instance does not have a public address, it seems reasonable to expect that the proxy could connect to the private address.

## Additional Context

This is what I get when I connect using the v1 proxy (this is a very old version installed with `gcloud components install cloud_sql_proxy` -- incidentally, it would be nice if this was updated):

```
$ cloud_sql_proxy -version
Cloud SQL Auth proxy: 1.27.0+darwin.arm64

$ cloud_sql_proxy -enable_iam_login -instances PROJECT_ID:REGION:INSTANCE_ID=tcp:9470
2022/12/27 10:32:18 current FDs rlimit set to 1048575, wanted limit is 8500. Nothing to do here.
2022/12/27 10:32:20 Listening on 127.0.0.1:9470 for PROJECT_ID:REGION:INSTANCE_ID
2022/12/27 10:32:20 Ready for new connections
2022/12/27 10:32:20 New connection for "PROJECT_ID:REGION:INSTANCE_ID"
2022/12/27 10:32:20 refreshing ephemeral certificate for instance PROJECT_ID:REGION:INSTANCE_ID
2022/12/27 10:32:20 Generated RSA key in 67.990208ms
2022/12/27 10:32:21 Scheduling refresh of ephemeral certificate in 59m2.640099s
```

This is the same output for a recent version of the v2 proxy (same instance):

```
$ cloud-sql-proxy --version
cloud-sql-proxy version 2.0.0-preview.4

$ cloud-sql-proxy     --auto-iam-authn     'PROJECT_ID:REGION:INSTANCE_ID?port=9470'
2022/12/27 10:31:15 Authorizing with Application Default Credentials
2022/12/27 10:31:16 [PROJECT_ID:REGION:INSTANCE_ID] Listening on 127.0.0.1:9470
2022/12/27 10:31:16 The proxy has started successfully and is ready for new connections!
2022/12/27 10:31:32 [PROJECT_ID:REGION:INSTANCE_ID] accepted connection from 127.0.0.1:50823
2022/12/27 10:31:32 [PROJECT_ID:REGION:INSTANCE_ID] failed to connect to instance: Config error: instance does not have IP of type "PUBLIC" (connection name = "PROJECT_ID:REGION:INSTANCE_ID")
```

**Comment by kurtisvg** [comment]
Hi @jawnsy,

Thanks for taking the time to open a feature request. 

The change from v1 to v2 was very much intentional, for 2 major reasons:
1. The original behavior was not intuitive -- we've had hundreds of support cases where the root cause was that the behavior was not predictable. Customers would assume they were connecting over private ip and really be connecting over public ip.
2. The original behavior was not static -- if someone added or remove an ip type it could change the behavior. For large scale deployments this could introduce issues with debugging; it created scenarios where instances of the proxy could have different behavior based on if they were started before/after the change. 

Connecting over private IP is a very intentional thing - you need to have access through a VPC which is generally not a straightforward task. By making the flag for private ip an explicit setting, the behavior is not just more straightforward, but also leaves us room to improve the feedback when the user fails to connect. 

If we do add something similar to this, it would probably be something like an `--auto-ip` option that would still require an explicit opt-in. However, we'd prefer not to at this time because we feel it's not a good choice for production.

**Comment by jawnsy** [comment]
That makes sense, thanks for the comprehensive explanation @kurtisvg!

Your explanation might be worth copying into the [migration guide](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/migration-guide.md)'s Notes column, to make it clearer that this was an intentional change/expected difference in behavior.
