### ISSUE TITLE
Supporting proxying to multiple Cloud SQL instances

### ISSUE THREAD

**Issue by digitalnomd** [GoogleCloudPlatform/cloud-sql-proxy#1715]
### Question

I'm working on vertically partitioning a Cloud SQL instance to multiple Cloud SQL instances. I'm currently using `cloud-sql-proxy` to connect to the first instance and wondering if it supports proxying to multiple instances. If not, I was planning on using the Cloud SQL Python connector to connect instead.

Does `cloud-sql-proxy` support connecting to multiple Cloud SQL instances? If so, what are the pros/cons of using the `cloud-sql-proxy` over the Python connector?

Thanks in advance!

**Comment by jackwotherspoon** [comment]
Hi @digitalnomd, thanks for the great question! 

The Cloud SQL Proxy does support connecting to multiple instances! You can do so through the following invocation:
```sh
./cloud-sql-proxy <INSTANCE_CONNECTION_NAME_1> <INSTANCE_CONNECTION_NAME_2>
```
You can read more detailed information about configuring connection to multiple instances in our [Basic Usage section of the README](https://github.com/GoogleCloudPlatform/cloud-sql-proxy#basic-usage).

In terms of pros/cons between the Proxy and a Connector library (Java, Node, Go, Python), it really comes down to preference as both perform the same job and have similar capabilities. 

The Proxy is language agnostic since it is a binary vs a Connector which is tied to a specific programming language. So if you are running something locally and prefer using a CLI like `psql` than maybe the Proxy is best for you. However, if you are comfortable with Python and would rather write code over use a CLI than maybe go with the Python Connector.

Another factor to consider is if you are looking to deploy your application, if you are looking to deploy your code as a Python app say to Cloud Run, Cloud Functions etc than the Python Connector would be easiest as a native integration. 

Hope this helps, have a great day!       
-- Jack

**Comment by jackwotherspoon** [comment]
Closing this as answered, but feel free to re-open if the answer did not clear things up for you.
