### ISSUE TITLE
cloudsql proxy examples for k8s-sidecar contain a race condition

### ISSUE THREAD

**Issue by digitalnomd** [GoogleCloudPlatform/cloud-sql-proxy#1757]
### Description

The examples provided assume that `cloud-sql-proxy` will always startup before your application container does. This might not always be true since your application could startup before `cloud-sql-proxy` does in which case you'd be unable to connect to your Cloud SQL instance.

### Potential Solution

I suggest adding an init container to the documentation that checks that cloud sql proxy is running before executing your application.

**Comment by hessjcg** [comment]
While the proxy usually starts up quickly, it is not instantaneous. There is a chance that the application container could attempt to open a connection to the proxy before the proxy container is listening for connections. 

Our best recommendation is to program your application's database connection logic to retry and backoff when attempting to connect to the database.  We recommend you use a connection pool library and configure it to handle retries on connection errors. This way your application will be resilient on startup and any time that connectivity to the proxy or the database is disrupted.  

Additionally, we will update the example to better demonstrate how to use k8s health checks so that pods only receive traffic after the proxy sidecar container is ready. 

You may also consider using the [Proxy Operator](https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator) which will configure the proxy sidecar container for you.
