### ISSUE TITLE
Cloud sql auth proxy sidecar in gke cluster - connecting to instance in separate vpc

### ISSUE THREAD

**Issue by nicholaslanger** [GoogleCloudPlatform/cloud-sql-proxy#1844]
### Question

@kurtisvg 

Hi Kurtis,

I watched your video https://www.youtube.com/watch?v=CNnzbNQgyzo and saw your responses here on this issue https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/395.

I believe you might be the perfect guy to help out with an issue I'm facing. 

My team and I are currently using a cloud sql auth proxy side car https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#proxy in our Apache Superset GKE cluster deployment to connect to a Cloud SQL PostgreSQL instance within the same VPC/project. 

We are attempting to connect an additional Cloud SQL PostgreSQL instance within the same project using the same cloud sql auth side car however the additional db we are trying to connect is in a separate VPC. 

We are using this image gcr.io/cloudsql-docker/gce-proxy:1.33.2 to run the side car and are running a command similar to this link https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/51cc2c6b4d5b369cb99f1a18fe679610b4f184e8/migration-guide.md?plain=1#L79 to provision the second connection to the proxy.

This fails with the following error:
* New connection for "[db instance connection name]"
* couldnt connect to "[db instance connection name]": dial tcp [private ip]:3307: connect: connection timed out

After reading your responses on https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/395 I thought the root of the issue was that the Cloud SQL PostgreSQL instance is hosted on an entirely different VPC so I decided to attempt to create a VPC peering between the two VPCs. However the peering is stuck in an "Inactive" status. 

My questions are as follows...
* Is my debugging thought process correct by needing to create a VPC peering? If not what should I do to make the proxy work between VPCs?
* If a VPC peering is the correct solution, what could be the culprit for the peering being hung up in an "Inactive" state?

Unrelated question:
*  Is the port specified when creating the proxy https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/51cc2c6b4d5b369cb99f1a18fe679610b4f184e8/migration-guide.md?plain=1#L79 just the port that the proxy connection is on locally? Does it not have to be the same port that the db is hosted on in Cloud SQL? (example: setting the port for the db to something different in the proxy connection as the dbs port on cloud sql is already in use in the proxy) The docs are unclear on this.

Thanks and I look forward to hearing back,

Nick

**Comment by jackwotherspoon** [comment]
Hi @nicholaslanger I am happy to try and help answer this for you (Kurtis no longer works at Google). 

This seems like a Cloud SQL Transitive VPC issue. I'll provide a bit of background context.

**Transitive VPC limitation:**
One limitation of VPC Network Peering is that VPC peering only broadcasts routes between **two VPCs that are directly peered**. As a result, VPC Peering isn’t transitive. For example, two networks that are each peered to an intermediary network are unable to communicate directly to one another.

In your instance you have provisioned a Cloud SQL instance with private IP from your VPC,  VPC B. Internally, Cloud SQL deploys the instance in its own managed VPC, the “Cloud SQL VPC”, VPC C and automatically peers it with the VPC you configured the instance with (VPC B). Any authorized Google Cloud resources in VPC B may route traffic to the Cloud SQL instances over private IP (this is what you have with your working VPC). However, if you have an additional separate VPC, VPC A, these Google Cloud resources will not be able to directly access your Cloud SQL resources over private IP through VPC B (intermediate VPC). Even if you’ve set up a peering connection between your VPC B and your VPC A ( your inactive peering), resources in VPC A will be unable to connect over private IP due to the nature of transitive VPC peering through private service access. 

![image](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/assets/32113413/9a87d652-9130-4044-9cb8-562fa0b87dd1)

One option that works well to solve this issue is deploying a SOCKS5 proxy as an intermediary between VPCs. One that works well with the Cloud SQL Auth Proxy is [dante](https://www.inet.no/dante/). Deploy that on a GCE instance in VPC B (your VPC that the Cloud SQL instance private IP is configured with) and then launch the Cloud SQL Auth Proxy like so (update your YAML):

```sh
ALL_PROXY=socks5:$DANTE_VM_IP_ADDR:8000 \
HTTPS_PROXY=socks5:$DANTE_VM_IP_ADDR:8000 \
    cloud-sql-proxy <INSTANCE_CONNECTION_NAME>
```

See the [Cloud SQL Auth proxy README](https://github.com/GoogleCloudPlatform/cloudsql-proxy#running-behind-a-socks5-proxy) for details. There's also a good [guide on running dante](https://www.digitalocean.com/community/tutorials/how-to-set-up-dante-proxy-on-ubuntu-20-04), and [another one](https://community.hetzner.com/tutorials/install-and-configure-danted-proxy-socks5) here.

Note: Make sure to [Configure your VPC's firewall](https://cloud.google.com/vpc/docs/firewalls) to allow TCP traffic from the appropriate IP address or range to the SOCKS server's configured port.

We are working on publishing a detailed Google Cloud docs page on this exact issue that will walk through the different possible solutions and step users through the required steps for each. Hoping this will help for future users facing a similar problem.

Have a great day and let me know if you have any follow-up questions 😄

**Comment by enocom** [comment]
I’m going to assume you’ve got what you needed here. Feel free to re open with more info otherwise.
