### ISSUE TITLE
VirusTotal flagging latest darwin-arm64 binary as malware

### ISSUE THREAD

**Issue by tedsilb** [GoogleCloudPlatform/cloud-sql-proxy#1977]
### Bug Description

Hi, just flagging that VirusTotal detects the [latest](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/releases/tag/v2.7.0) darwin-arm64 binary 
(hash `9e47a9cbd96d572b1fd51e9902e1c2a449c43e55cdd038f77941d795c603b639`) as containing malware (`Google: Ikarus - Trojan.OSX.Psw`). I reanalyzed on VirusTotal and it produced the same finding.

VirusTotal link: https://www.virustotal.com/gui/file/9e47a9cbd96d572b1fd51e9902e1c2a449c43e55cdd038f77941d795c603b639/detection/f-9e47a9cbd96d572b1fd51e9902e1c2a449c43e55cdd038f77941d795c603b639-1695370063

### Steps to reproduce?

scan with virustotal

### Environment

darwin-arm64

**Comment by enocom** [comment]
Thanks @tedsilb. I'll investigate and respond here.

**Comment by enocom** [comment]
Bumping this down as it appears to be a false positive. Investigating further.

**Comment by enocom** [comment]
This is definitely a false positive, but it's still concerning that it's happening.

**Comment by enocom** [comment]
Just to be clear:

1. All our builds are completed on Cloud Build using latest Go and source only. There are no binaries included in our build.
2. We run govulncheck against every commit.
3. We use container scanning for every release.

Our latest release has no reported vulnerabilities by govulncheck or in our default image (based on distroless). It's not clear what's getting flagged in VirusTotal, but we have reason to believe this is a false positive.

**Comment by enocom** [comment]
I suspect we might be getting flagged because we don't notorize the binary with Apple. This might be a duplicate in effect of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1712.

**Comment by hessjcg** [comment]
In reading the [VirusTotal behavior report](https://www.virustotal.com/gui/file/08025475bd7daac6f0d5779dbe3f3f8e9ea6a5220e0c90b30225150b98682302/behavior)  carefully for the amd64 binary, the virus total test result shows our binary attempting to access /etc/master.passwd and the wifi settings. 

Of course, I tried to reproduce this behavior and could not because our binary does not actually do these things.

The [virustotal scan details](https://vtbehaviour.commondatastorage.googleapis.com/08025475bd7daac6f0d5779dbe3f3f8e9ea6a5220e0c90b30225150b98682302_VirusTotal%20Box%20of%20Apples.html?GoogleAccessId=758681729565-rc7fgq07icj8c9dm2gi34a4cckv235v1@developer.gserviceaccount.com&Expires=1695754338&Signature=FijbtHT8ztRKNP5VB0j%2B4dY2dCXSYJrzwM%2FJBA%2BINAvfOjz0Ejl%2Fd6kkpJkRm3SwPObjRyFdRFgE%0A50Dew%2F1ry2Cn1Zk%2FZbocUi1djeHMMM0mMSD7F%2ByDqll9EcC%2BU4CKP0oDINKQ3ggoVmuMQuOuKV2l%0ADJ7OTANDnk96otE2T3Rqn5xWp4DFQjV9%2Bdq6CHzJHjbDzLki0EV%2BVxEFrIP2VYiTxDkpTbIxiwbj%0AgOmoYnOUpTGiYNSuNroaa8s6ji5hXYi%2BHdz2TkigRKJI98vplw41jA95VCooqeAXng7%2BRGFVgq01%0AtqV7XYDFSa88Vgq7mKJ9n9eIEaBOkpj9bbn%2FPQ%3D%3D&response-content-type=text%2Fhtml;)  Shows that the various sensitive files like /etc/master.passwd and /Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist were opened by macosx components. They weren't opened by our process.

We are investigating how to reach VirusTotal to verify that this is a false positive result.

**Comment by enocom** [comment]
Confirmed. This was a false positive across a few security scanners.

https://www.virustotal.com/gui/file/04cea1a08be2bbbe8bd07e2b2e5430f88d627aa1839fdc8efd2092dd89c6f8de/
